- name: start MySQL slave process
  mysql_replication:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: startslave
  when: inventory_hostname == 'docker-host2' or inventory_hostname == 'docker-host3'
