---
    - name: "Create {{ mysql_replicator_user }} user with all privileges and grant for replication"
      mysql_user:
        name: "{{ mysql_replicator_user }}"
        password: "{{ mysql_replicator_password }}"
        host: "%"
        priv: "*.*:ALL,GRANT"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: inventory_hostname == 'docker-host1'
    
    - name: Reload privilege tables
      mysql_query:
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        query: FLUSH PRIVILEGES
      when: inventory_hostname == 'docker-host1'
      